### ISSUE TITLE
desculpa Rafa não tenho nenhuma rede social suakkkk

### ISSUE THREAD

**Issue by lunaperegrina** [mazarafa/Innerbloom#4]
Mas eu queria te perguntar (ja q vc pesquisou sobre o assunto o suficiente pra criar um bot) se, depois de 3 anos, a forma como a permissão da consulta funciona segue gratuita. To querendo fazer consultas pra retornar dados da pessoa através do CPF, mas pelo que vi preciso pagar 

![image](https://github.com/rafinhadufluxo/Innerbloom/assets/57403682/36c626d2-0901-4f47-8ae6-72bad6fdcc39)

**Comment by rafinhadufluxo** [comment]
Olá, tudo bem? Posso conversar sim sobre isso, é bom compartilhar conhecimento hehe
pode me seguir no twitter ou telegram que é @rafinhadufluxo
